language: swift
osx_image: xcode9.1
script:
  - ./scripts/update_geth.sh
  - xcodebuild test -project KinSDK/KinSDK.xcodeproj -scheme KinTestHost -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.1'
